name: Mark 1 - Your First CNN
experiment: YourFirstCNN
metrics:
  halflife: 8 # smoothing option
model:
  batchsize: 32
  epochs: 1
  n_labels: 5
train:
  dataset:
    type: ImageFolderDataset
    path: dataset/train
    res: 180
  dataloader:
    num_workers: 1 # You may want to increase this if not preloaded
val:
  dataset:
    type: ImageFolderDataset
    path: dataset/val
    res: 180
test:
  dataset:
    type: ImageFolderDataset
    path: dataset/test
    res: 180